### ISSUE TITLE
Fails to parse a top-level object

### ISSUE THREAD

**Issue by aaemnnosttv** [deliciousbrains/serialized-editor#5]
The following input fails

```
O:8:"stdClass":0:{}
```

> Invalid serialized data

This is because the parsed JSON string it produces is not valid JSON  
`SyntaxError: Unexpected token , in JSON at position 52`
```
{"type": "O", "value": "stdClass", "isObject": true},{"type": "a", "values": [], "isObject": true}
```

**Comment by gilbitron** [comment]
Fixed in https://github.com/deliciousbrains/serialized-editor/commit/b96a5cfb95c5a008ec9c5eb513471b6fac6de894 and https://github.com/deliciousbrains/serialized-editor/commit/ba61e9e2fc03096ca44ccf25489ebc873a12a946
